name: Build External Packages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/check-external-updates.yml'
      - '**.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to build'
        required: true
        type: choice
        options:
          - indi
      suite:
        description: 'APT suite to publish to'
        required: true
        default: 'testing'
        type: choice
        options:
          - testing
          - stable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Filter changed packages
      uses: dorny/paths-filter@v3
      id: package-change
      with:
        filters: |
          indi:
            - 'packages/indi/**'

    - name: Set up QEMU
      if: |
        steps.package-change.outputs.indi == 'true' ||
        github.event.inputs.package == 'indi'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Build INDI
      if: |
        steps.package-change.outputs.indi == 'true' ||
        github.event.inputs.package == 'indi'
      run: |
        echo "Building INDI package..."
        docker run --rm --platform linux/arm64 \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          debian:trixie-slim \
          bash -c '
            set -e
            export DEBIAN_FRONTEND=noninteractive
            export BUILD_DIR=/workspace/build
            export OUTPUT_DIR=/workspace/build/output

            echo "Installing base build tools..."
            apt-get update
            apt-get install -y debhelper devscripts cdbs cmake build-essential git

            echo "Building INDI..."
            ./scripts/build-package.sh indi

            echo "Build artifacts:"
            ls -lh /workspace/build/output/
          '

    - name: Upload package artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: build/output/*.deb
        if-no-files-found: warn

    - name: Upload build info
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-info
        path: |
          build/output/*.buildinfo
          build/output/*.changes
        if-no-files-found: warn

    - name: Auto-commit to astroberry64-repo
      if: |
        (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
        github.event_name == 'workflow_dispatch'
      env:
        GH_TOKEN: ${{ secrets.ASTROBERRY64_REPO_TOKEN }}
        SUITE: ${{ github.event.inputs.suite || 'testing' }}
      run: |
        # Only proceed if we have .deb files
        if ! ls build/output/*.deb 1> /dev/null 2>&1; then
          echo "No .deb files found, skipping deployment"
          exit 0
        fi

        # Clone the repo with token authentication
        git clone https://x-access-token:${GH_TOKEN}@github.com/astroberry64/astroberry64-repo.git /tmp/repo
        cd /tmp/repo

        # Configure git
        git config user.name "Astroberry64 Bot"
        git config user.email "bot@astroberry64.github.io"

        # Add all packages to the suite
        for deb in ${{ github.workspace }}/build/output/*.deb; do
          if [ -f "$deb" ]; then
            echo "Adding $(basename $deb) to ${SUITE} suite..."
            ./add-package.sh "$deb" "${SUITE}"
          fi
        done

        # Commit and push
        git add dists/trixie-${SUITE} pool
        git commit -m "Auto-add external packages to ${SUITE} suite"$'\n\n'"Built from ${{ github.repository }}@${{ github.sha }}"$'\n\n'"🤖 Automated build via GitHub Actions" || echo "No changes to commit"
        git push origin main || echo "Nothing to push"
